// <auto-generated />
namespace RobokaBimeBazar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_phone_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_phone_number));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050714144_add_phone_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
