// <auto-generated />
namespace RobokaBimeBazar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_user_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_user_info));
        
        string IMigrationMetadata.Id
        {
            get { return "201811051410505_update_user_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
